Accepts ma feature space and provides an introspective results to identify characteristics and guide further analysis. A first layer, high level review of a given dataset to assist in building useful models.

# Time series analysis

In [1]:
import sys, os
from pathlib import Path
from datetime import datetime, date

current_path = Path.cwd().resolve()
project_root = current_path.parents[2]  
sys.path.append(str(project_root))
project_root

WindowsPath('C:/Users/micha/OneDrive/Documents/code/pyfi')

In [2]:
from pyfi.lib.retrievers import fred
data = fred.get_matrix(ids = ['VIXCLS', *fred.IDS_STANDARD])
data

            VIXCLS      GDP  CPIAUCSL  UNRATE  BAMLH0A0HYM2    SP500
date
1946-01-01     NaN      NaN       NaN     NaN           NaN      NaN
1946-04-01     NaN      NaN       NaN     NaN           NaN      NaN
1946-07-01     NaN      NaN       NaN     NaN           NaN      NaN
1946-10-01     NaN      NaN       NaN     NaN           NaN      NaN
1947-01-01     NaN  243.164     21.48     NaN           NaN      NaN
...            ...      ...       ...     ...           ...      ...
2024-11-18   15.58      NaN       NaN     NaN          2.72  5893.62
2024-11-19   16.35      NaN       NaN     NaN          2.69  5916.98
2024-11-20   17.16      NaN       NaN     NaN          2.67  5917.11
2024-11-21   16.87      NaN       NaN     NaN          2.61  5948.71
2024-11-22     NaN      NaN       NaN     NaN           NaN  5969.34

[9837 rows x 6 columns]

In [3]:
from pyfi.lib.datasci.time_series.timeseries import TimeSeries, Frequency, AggFunc
ts = TimeSeries(df=data, dep_var = 'GDP')
ts

In [4]:
ts.group(frequency=Frequency.MONTHLY, aggfunc=AggFunc.LAST)

In [5]:
ts.df = ts.df.dropna(how='any', axis=0)

In [6]:
ts.get_stationarity()

,id,ADF Statistic,p-value,lags,n-obs,Critical Value 1%,Critical Value 5%,Critical Value 10%,bool
0,VIXCLS,-3.137231,0.023918,0.0,38.0,-3.615509,-2.941262,-2.609200,True
1,GDP,1.041473,0.994685,0.0,38.0,-3.615509,-2.941262,-2.609200,False
2,CPIAUCSL,0.200527,0.972291,2.0,36.0,-3.626652,-2.945951,-2.611671,False
3,UNRATE,-3.454637,0.009231,0.0,38.0,-3.615509,-2.941262,-2.609200,True
4,BAMLH0A0HYM2,-2.955610,0.039253,3.0,35.0,-3.632743,-2.948510,-2.613017,True
5,SP500,2.029735,0.998710,9.0,29.0,-3.679060,-2.967882,-2.623158,False

In [7]:
coef, pval, tall = ts.get_correlation()

In [8]:
coef

                VIXCLS       GDP  CPIAUCSL    UNRATE  BAMLH0A0HYM2     SP500
VIXCLS        1.000000  0.169225  0.182182  0.499855      0.314038  0.225276
GDP           0.169225  1.000000  0.994724 -0.293728     -0.429279  0.949623
CPIAUCSL      0.182182  0.994724  1.000000 -0.253104     -0.366189  0.930346
UNRATE        0.499855 -0.293728 -0.253104  1.000000      0.541370 -0.165485
BAMLH0A0HYM2  0.314038 -0.429279 -0.366189  0.541370      1.000000 -0.498565
SP500         0.225276  0.949623  0.930346 -0.165485     -0.498565  1.000000

In [9]:
pval

                VIXCLS       GDP  CPIAUCSL    UNRATE  BAMLH0A0HYM2     SP500
VIXCLS        0.000000  0.303069  0.266985  0.001195      0.051543  0.167934
GDP           0.303069  0.000000  0.000000  0.069536      0.006390  0.000000
CPIAUCSL      0.266985  0.000000  0.000000  0.120030      0.021864  0.000000
UNRATE        0.001195  0.069536  0.120030  0.000000      0.000372  0.314036
BAMLH0A0HYM2  0.051543  0.006390  0.021864  0.000372      0.000000  0.001236
SP500         0.167934  0.000000  0.000000  0.314036      0.001236  0.000000

In [10]:
tall

       Feature_1     Feature_2  Coefficient       P_Value
0         VIXCLS        VIXCLS     1.000000           NaN
1         VIXCLS           GDP     0.169225  3.030690e-01
2         VIXCLS      CPIAUCSL     0.182182  2.669848e-01
3         VIXCLS        UNRATE     0.499855  1.195192e-03
4         VIXCLS  BAMLH0A0HYM2     0.314038  5.154322e-02
5         VIXCLS         SP500     0.225276  1.679337e-01
6            GDP           GDP     1.000000           NaN
7            GDP      CPIAUCSL     0.994724  3.373156e-38
8            GDP        UNRATE    -0.293728  6.953641e-02
9            GDP  BAMLH0A0HYM2    -0.429279  6.389983e-03
10           GDP         SP500     0.949623  3.100974e-20
11      CPIAUCSL      CPIAUCSL     1.000000           NaN
12      CPIAUCSL        UNRATE    -0.253104  1.200304e-01
13      CPIAUCSL  BAMLH0A0HYM2    -0.366189  2.186384e-02
14      CPIAUCSL         SP500     0.930346  1.055106e-17
15        UNRATE        UNRATE     1.000000           NaN
16        UNRATE  BAMLH0A0HYM2     0.541370  3.723974e-04
17        UNRATE         SP500    -0.165485  3.140358e-01
18  BAMLH0A0HYM2  BAMLH0A0HYM2     1.000000           NaN
19  BAMLH0A0HYM2         SP500    -0.498565  1.236422e-03
20         SP500         SP500     1.000000           NaN

In [11]:
coef, pval, tall = ts.get_cointegration()

In [12]:
coef

                VIXCLS       GDP  CPIAUCSL    UNRATE  BAMLH0A0HYM2     SP500
VIXCLS             NaN -3.299229 -3.270883 -3.559530     -2.862638 -3.443978
GDP          -0.145292       NaN -3.656479  0.242873     -0.736077 -3.173143
CPIAUCSL      0.198050 -3.615594       NaN -0.000362     -0.598549 -1.052647
UNRATE       -3.880756 -3.530934 -3.601351       NaN     -3.047224 -3.498942
BAMLH0A0HYM2 -2.536606 -3.077612 -3.117810 -3.014779           NaN -3.111678
SP500         0.527027 -2.849108 -0.774093  0.324299     -0.423121       NaN

In [13]:
pval

                VIXCLS       GDP  CPIAUCSL    UNRATE  BAMLH0A0HYM2     SP500
VIXCLS             NaN  0.054841  0.058852  0.027471      0.146566  0.037695
GDP           0.981891       NaN  0.020823  0.990197      0.942602  0.074535
CPIAUCSL      0.989579  0.023434       NaN  0.985892      0.956529  0.892399
UNRATE        0.010543  0.029750  0.024407       NaN      0.099403  0.032489
BAMLH0A0HYM2  0.263168  0.092888  0.084781  0.106734           NaN  0.085981
SP500         0.992821  0.150559  0.938024  0.991158      0.969376       NaN

In [14]:
tall

       Feature_1     Feature_2  Coefficient       P_Value
0         VIXCLS        VIXCLS     1.000000           NaN
1         VIXCLS           GDP     0.169225  3.030690e-01
2         VIXCLS      CPIAUCSL     0.182182  2.669848e-01
3         VIXCLS        UNRATE     0.499855  1.195192e-03
4         VIXCLS  BAMLH0A0HYM2     0.314038  5.154322e-02
5         VIXCLS         SP500     0.225276  1.679337e-01
6            GDP           GDP     1.000000           NaN
7            GDP      CPIAUCSL     0.994724  3.373156e-38
8            GDP        UNRATE    -0.293728  6.953641e-02
9            GDP  BAMLH0A0HYM2    -0.429279  6.389983e-03
10           GDP         SP500     0.949623  3.100974e-20
11      CPIAUCSL      CPIAUCSL     1.000000           NaN
12      CPIAUCSL        UNRATE    -0.253104  1.200304e-01
13      CPIAUCSL  BAMLH0A0HYM2    -0.366189  2.186384e-02
14      CPIAUCSL         SP500     0.930346  1.055106e-17
15        UNRATE        UNRATE     1.000000           NaN
16        UNRATE  BAMLH0A0HYM2     0.541370  3.723974e-04
17        UNRATE         SP500    -0.165485  3.140358e-01
18  BAMLH0A0HYM2  BAMLH0A0HYM2     1.000000           NaN
19  BAMLH0A0HYM2         SP500    -0.498565  1.236422e-03
20         SP500         SP500     1.000000           NaN

In [15]:
ts.decompose(var=ts.num_cols[0])

                Trend  Seasonal  Residuals
dt
2015-10-31  15.782857  0.670898  -1.383755
2016-01-31  15.224286 -1.830245   6.805959
2016-04-30  14.858571 -3.430531   4.271959
2016-07-31  14.672857 -3.521388   0.718531
2016-10-31  13.985714  2.537755   0.536531
2017-01-31  12.554286  3.330684  -3.894969
2017-04-30  12.245714  2.242827  -3.668541
2017-07-31  12.825714  0.670898  -3.236612
2017-10-31  12.221429 -1.830245  -0.211184
2018-01-31  13.541429 -3.430531   3.429102
2018-04-30  14.362857 -3.521388   5.088531
2018-07-31  14.771429  2.537755  -4.479184
2018-10-31  15.620000  3.330684   2.279316
2019-01-31  15.574286  2.242827  -1.247112
2019-04-30  15.990000  0.670898  -3.540898
2019-07-31  19.035714 -1.830245  -1.085469
2019-10-31  19.497143 -3.430531  -2.846612
2020-01-31  22.561429 -3.521388  -0.200041
2020-04-30  25.414286  2.537755   6.197959
2020-07-31  25.770000  3.330684  -4.640684
2020-10-31  26.487143  2.242827   9.290031
2021-01-31  26.118571  0.670898   6.300531
2021-04-30  24.787143 -1.830245  -4.346898
2021-07-31  26.064286 -3.430531  -4.393755
2021-10-31  23.680000 -3.521388  -3.898612
2022-01-31  22.650000  2.537755  -0.357755
2022-04-30  22.762857  3.330684   7.306459
2022-07-31  22.411429  2.242827  -3.324255
2022-10-31  22.035714  0.670898   3.173388
2023-01-31  21.080000 -1.830245   0.150245
2023-04-30  18.358571 -3.430531   0.851959
2023-07-31  17.547143 -3.521388  -0.395755
2023-10-31  16.187143  2.537755  -0.584898

In [16]:
ratio, z_score, adf = ts.get_feature_ratios()

In [17]:
ratio

,VIXCLS/GDP,VIXCLS/CPIAUCSL,VIXCLS/UNRATE,VIXCLS/BAMLH0A0HYM2,VIXCLS/SP500,GDP/CPIAUCSL,GDP/UNRATE,GDP/BAMLH0A0HYM2,GDP/SP500,CPIAUCSL/UNRATE,CPIAUCSL/BAMLH0A0HYM2,CPIAUCSL/SP500,UNRATE/BAMLH0A0HYM2,UNRATE/SP500,BAMLH0A0HYM2/SP500
dt,,,,,,,,,,,,,,,
1946-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-01-01,NaN,NaN,NaN,NaN,NaN,11.320484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-11-18,NaN,NaN,NaN,5.727941,0.002644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000462
2024-11-19,NaN,NaN,NaN,6.078067,0.002763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000455
2024-11-20,NaN,NaN,NaN,6.426966,0.002900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000451
2024-11-21,NaN,NaN,NaN,6.463602,0.002836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000439
2024-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
z_score

,VIXCLS/GDP,VIXCLS/CPIAUCSL,VIXCLS/UNRATE,VIXCLS/BAMLH0A0HYM2,VIXCLS/SP500,GDP/CPIAUCSL,GDP/UNRATE,GDP/BAMLH0A0HYM2,GDP/SP500,CPIAUCSL/UNRATE,CPIAUCSL/BAMLH0A0HYM2,CPIAUCSL/SP500,UNRATE/BAMLH0A0HYM2,UNRATE/SP500,BAMLH0A0HYM2/SP500
dt,,,,,,,,,,,,,,,
1946-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-01-01,NaN,NaN,NaN,NaN,NaN,-1.416249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-11-18,NaN,NaN,NaN,1.097970,-1.118588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.320821
2024-11-19,NaN,NaN,NaN,1.336782,-1.078366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.329409
2024-11-20,NaN,NaN,NaN,1.574758,-1.032387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.333633
2024-11-21,NaN,NaN,NaN,1.599746,-1.053945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.349187
2024-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
adf

,id,ADF Statistic,p-value,lags,n-obs,Critical Value 1%,Critical Value 5%,Critical Value 10%,bool
0,VIXCLS/GDP,-3.052583,0.030267,0.0,18.0,-3.859073,-3.042046,-2.660906,True
1,VIXCLS/CPIAUCSL,-2.979070,0.036896,0.0,18.0,-3.859073,-3.042046,-2.660906,True
2,VIXCLS/UNRATE,-3.089264,0.027358,0.0,18.0,-3.859073,-3.042046,-2.660906,True
3,VIXCLS/BAMLH0A0HYM2,-1.807583,0.376703,0.0,18.0,-3.859073,-3.042046,-2.660906,False
4,VIXCLS/SP500,-3.077292,0.028280,0.0,18.0,-3.859073,-3.042046,-2.660906,True
5,GDP/CPIAUCSL,-0.744654,0.834842,0.0,18.0,-3.859073,-3.042046,-2.660906,False
6,GDP/UNRATE,-1.513480,0.526833,0.0,18.0,-3.859073,-3.042046,-2.660906,False
7,GDP/BAMLH0A0HYM2,4.160787,1.000000,6.0,12.0,-4.137829,-3.154972,-2.714477,False
8,GDP/SP500,-0.838862,0.807439,6.0,12.0,-4.137829,-3.154972,-2.714477,False
9,CPIAUCSL/UNRATE,-1.715963,0.422907,0.0,18.0,-3.859073,-3.042046,-2.660906,False
10,CPIAUCSL/BAMLH0A0HYM2,4.476086,1.000000,6.0,12.0,-4.137829,-3.154972,-2.714477,False
11,CPIAUCSL/SP500,-1.499484,0.533767,6.0,12.0,-4.137829,-3.154972,-2.714477,False
12,UNRATE/BAMLH0A0HYM2,-2.192944,0.208816,0.0,18.0,-3.859073,-3.042046,-2.660906,False
13,UNRATE/SP500,-2.582442,0.096681,0.0,18.0,-3.859073,-3.042046,-2.660906,False
14,BAMLH0A0HYM2/SP500,0.705577,0.989949,6.0,12.0,-4.137829,-3.154972,-2.714477,False

# Regression

In [20]:
summary, spread, spread_z, spread_adf = ts.get_regression_spread()

In [21]:
summary

,ts1,ts2,alpha,beta,f_statistic,r_squared,p_value_intercept,p_value_coefficient,id
0,BAMLH0A0HYM2,CPIAUCSL,301.44,-8.33,5.73,0.13,0.00,0.02,BAMLH0A0HYM2_CPIAUCSL
1,BAMLH0A0HYM2,GDP,28468.29,-1362.79,8.36,0.18,0.00,0.01,BAMLH0A0HYM2_GDP
2,BAMLH0A0HYM2,SP500,5230.82,-447.64,12.24,0.25,0.00,0.00,BAMLH0A0HYM2_SP500
3,BAMLH0A0HYM2,UNRATE,0.43,1.00,15.34,0.29,0.71,0.00,BAMLH0A0HYM2_UNRATE
4,BAMLH0A0HYM2,VIXCLS,9.92,1.91,4.05,0.10,0.03,0.05,BAMLH0A0HYM2_VIXCLS
5,CPIAUCSL,BAMLH0A0HYM2,8.64,-0.02,5.73,0.13,0.00,0.02,CPIAUCSL_BAMLH0A0HYM2
6,CPIAUCSL,GDP,-14298.88,138.88,3478.51,0.99,0.00,0.00,CPIAUCSL_GDP
7,CPIAUCSL,SP500,-6463.49,36.74,238.18,0.87,0.00,0.00,CPIAUCSL_SP500
8,CPIAUCSL,UNRATE,10.27,-0.02,2.53,0.06,0.01,0.12,CPIAUCSL_UNRATE
9,CPIAUCSL,VIXCLS,5.36,0.05,1.27,0.03,0.64,0.27,CPIAUCSL_VIXCLS
10,GDP,BAMLH0A0HYM2,7.42,-0.00,8.36,0.18,0.00,0.01,GDP_BAMLH0A0HYM2
11,GDP,CPIAUCSL,104.66,0.01,3478.51,0.99,0.00,0.00,GDP_CPIAUCSL
12,GDP,SP500,-2772.39,0.27,339.72,0.90,0.00,0.00,GDP_SP500
13,GDP,UNRATE,8.67,-0.00,3.49,0.09,0.00,0.07,GDP_UNRATE
14,GDP,VIXCLS,10.99,0.00,1.09,0.03,0.13,0.30,GDP_VIXCLS
15,SP500,BAMLH0A0HYM2,6.19,-0.00,12.24,0.25,0.00,0.00,SP500_BAMLH0A0HYM2
16,SP500,CPIAUCSL,187.91,0.02,238.18,0.87,0.00,0.00,SP500_CPIAUCSL
17,SP500,GDP,11518.89,3.36,339.72,0.90,0.00,0.00,SP500_GDP
18,SP500,UNRATE,5.93,-0.00,1.04,0.03,0.00,0.31,SP500_UNRATE
19,SP500,VIXCLS,13.30,0.00,1.98,0.05,0.00,0.17,SP500_VIXCLS
20,UNRATE,BAMLH0A0HYM2,2.97,0.29,15.34,0.29,0.00,0.00,UNRATE_BAMLH0A0HYM2
21,UNRATE,CPIAUCSL,279.97,-3.11,2.53,0.06,0.00,0.12,UNRATE_CPIAUCSL
22,UNRATE,GDP,24929.86,-503.93,3.49,0.09,0.00,0.07,UNRATE_GDP
23,UNRATE,SP500,3658.33,-80.30,1.04,0.03,0.00,0.31,UNRATE_SP500
24,UNRATE,VIXCLS,10.38,1.65,12.32,0.25,0.00,0.00,UNRATE_VIXCLS
25,VIXCLS,BAMLH0A0HYM2,3.43,0.05,4.05,0.10,0.00,0.05,VIXCLS_BAMLH0A0HYM2
26,VIXCLS,CPIAUCSL,252.56,0.68,1.27,0.03,0.00,0.27,VIXCLS_CPIAUCSL
27,VIXCLS,GDP,20891.60,88.13,1.09,0.03,0.00,0.30,VIXCLS_GDP
28,VIXCLS,SP500,2664.59,33.18,1.98,0.05,0.00,0.17,VIXCLS_SP500
29,VIXCLS,UNRATE,2.04,0.15,12.32,0.25,0.02,0.00,VIXCLS_UNRATE

In [22]:
spread

           date                     id      value
0    2015-01-31  BAMLH0A0HYM2_CPIAUCSL -22.895766
1    2015-04-30  BAMLH0A0HYM2_CPIAUCSL -26.999456
2    2015-07-31  BAMLH0A0HYM2_CPIAUCSL -18.776125
3    2015-10-31  BAMLH0A0HYM2_CPIAUCSL -14.580867
4    2016-01-31  BAMLH0A0HYM2_CPIAUCSL   0.908508
...         ...                    ...        ...
1165 2023-07-31          VIXCLS_UNRATE  -0.603965
1166 2023-10-31          VIXCLS_UNRATE  -0.988271
1167 2024-01-31          VIXCLS_UNRATE  -0.513211
1168 2024-04-30          VIXCLS_UNRATE  -0.510461
1169 2024-07-31          VIXCLS_UNRATE  -0.218190

[1170 rows x 3 columns]

In [23]:
spread_z

           date                     id     value
0    2015-01-31  BAMLH0A0HYM2_CPIAUCSL -0.966234
1    2015-04-30  BAMLH0A0HYM2_CPIAUCSL -1.139415
2    2015-07-31  BAMLH0A0HYM2_CPIAUCSL -0.792379
3    2015-10-31  BAMLH0A0HYM2_CPIAUCSL -0.615333
4    2016-01-31  BAMLH0A0HYM2_CPIAUCSL  0.038340
...         ...                    ...       ...
1165 2023-07-31          VIXCLS_UNRATE -0.336506
1166 2023-10-31          VIXCLS_UNRATE -0.550626
1167 2024-01-31          VIXCLS_UNRATE -0.285941
1168 2024-04-30          VIXCLS_UNRATE -0.284409
1169 2024-07-31          VIXCLS_UNRATE -0.121567

[1170 rows x 3 columns]

In [24]:
spread_adf

,id,ADF Statistic,p-value,lags,n-obs,Critical Value 1%,Critical Value 5%,Critical Value 10%,bool
0,BAMLH0A0HYM2_CPIAUCSL,-0.339725,0.919687,1.0,37.0,-3.620918,-2.943539,-2.610400,False
1,BAMLH0A0HYM2_GDP,-0.416000,0.907393,1.0,37.0,-3.620918,-2.943539,-2.610400,False
2,BAMLH0A0HYM2_SP500,-0.315241,0.923318,1.0,37.0,-3.620918,-2.943539,-2.610400,False
3,BAMLH0A0HYM2_UNRATE,-3.005319,0.034401,0.0,38.0,-3.615509,-2.941262,-2.609200,True
4,BAMLH0A0HYM2_VIXCLS,-2.823739,0.054962,0.0,38.0,-3.615509,-2.941262,-2.609200,False
5,CPIAUCSL_BAMLH0A0HYM2,-3.074832,0.028473,0.0,38.0,-3.615509,-2.941262,-2.609200,True
6,CPIAUCSL_GDP,-3.606562,0.005637,0.0,38.0,-3.615509,-2.941262,-2.609200,True
7,CPIAUCSL_SP500,-1.210820,0.668924,9.0,29.0,-3.679060,-2.967882,-2.623158,False
8,CPIAUCSL_UNRATE,-3.552296,0.006741,0.0,38.0,-3.615509,-2.941262,-2.609200,True
9,CPIAUCSL_VIXCLS,-3.224302,0.018620,0.0,38.0,-3.615509,-2.941262,-2.609200,True
10,GDP_BAMLH0A0HYM2,-3.035546,0.031706,0.0,38.0,-3.615509,-2.941262,-2.609200,True
11,GDP_CPIAUCSL,-3.566675,0.006431,0.0,38.0,-3.615509,-2.941262,-2.609200,True
12,GDP_SP500,-2.798707,0.058459,2.0,36.0,-3.626652,-2.945951,-2.611671,False
13,GDP_UNRATE,-3.482614,0.008445,0.0,38.0,-3.615509,-2.941262,-2.609200,True
14,GDP_VIXCLS,-3.252419,0.017144,0.0,38.0,-3.615509,-2.941262,-2.609200,True
15,SP500_BAMLH0A0HYM2,-3.069410,0.028901,0.0,38.0,-3.615509,-2.941262,-2.609200,True
16,SP500_CPIAUCSL,-1.597460,0.484869,9.0,29.0,-3.679060,-2.967882,-2.623158,False
17,SP500_GDP,-3.257611,0.016883,6.0,32.0,-3.653520,-2.957219,-2.617588,True
18,SP500_UNRATE,-3.451452,0.009325,0.0,38.0,-3.615509,-2.941262,-2.609200,True
19,SP500_VIXCLS,-3.393911,0.011168,0.0,38.0,-3.615509,-2.941262,-2.609200,True
20,UNRATE_BAMLH0A0HYM2,-2.966563,0.038137,3.0,35.0,-3.632743,-2.948510,-2.613017,True
21,UNRATE_CPIAUCSL,0.105639,0.966444,0.0,38.0,-3.615509,-2.941262,-2.609200,False
22,UNRATE_GDP,1.293745,0.996574,2.0,36.0,-3.626652,-2.945951,-2.611671,False
23,UNRATE_SP500,0.485859,0.984437,0.0,38.0,-3.615509,-2.941262,-2.609200,False
24,UNRATE_VIXCLS,-3.510935,0.007711,0.0,38.0,-3.615509,-2.941262,-2.609200,True
25,VIXCLS_BAMLH0A0HYM2,-2.496657,0.116290,0.0,38.0,-3.615509,-2.941262,-2.609200,False
26,VIXCLS_CPIAUCSL,0.356119,0.979778,0.0,38.0,-3.615509,-2.941262,-2.609200,False
27,VIXCLS_GDP,0.544557,0.986166,1.0,37.0,-3.620918,-2.943539,-2.610400,False
28,VIXCLS_SP500,0.813643,0.991853,5.0,33.0,-3.646135,-2.954127,-2.615968,False
29,VIXCLS_UNRATE,-3.827922,0.002634,0.0,38.0,-3.615509,-2.941262,-2.609200,True

# Feature Engine